# Generated by Django 5.2.17 on 2026-09-23 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrator"),
                    ("FACULTY", "Faculty"),
                    ("LIBRARIAN", "Librarian"),
                    ("STUDENT", "Student"),
                    ("PARENT", "Parent"),
                ],
                default="STUDENT",
                max_length=10,
            ),
        ),
    ]
