# Generated by Django 5.2.17 on 2026-09-23 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_seed_roles_and_assign_existing_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentDocument",
            fields=[
                ("document_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("document_type", models.CharField(max_length=80)),
                ("file_url", models.URLField()),
                ("status", models.CharField(default="PENDING", max_length=30)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
        ),
    ]
