# Generated by Django 5.2.17 on 2026-09-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_studentdocument"),
    ]

    operations = [
        migrations.AlterField(
            model_name="employee",
            name="employee_code",
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="studentprofile",
            name="current_roll_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
