# Generated by Django 5.2.17 on 2026-09-25 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0007_alter_employee_employee_code_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="parentprofile",
            name="children",
        ),
        migrations.RemoveField(
            model_name="parentprofile",
            name="user",
        ),
        migrations.RemoveField(
            model_name="parentstudent",
            name="parent",
        ),
        migrations.RemoveField(
            model_name="parentstudent",
            name="student",
        ),
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[
                    ("ADMIN", "Administrator"),
                    ("FACULTY", "Faculty"),
                    ("STUDENT", "Student"),
                ],
                default="STUDENT",
                max_length=10,
            ),
        ),
        migrations.DeleteModel(
            name="LibrarianProfile",
        ),
        migrations.DeleteModel(
            name="ParentProfile",
        ),
        migrations.DeleteModel(
            name="ParentStudent",
        ),
    ]
