# Generated by Django 5.2.17 on 2026-09-26 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0008_remove_parentprofile_children_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="personaddress",
            name="address",
        ),
        migrations.RemoveField(
            model_name="auditlog",
            name="user",
        ),
        migrations.AlterUniqueTogether(
            name="facultysalary",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="facultysalary",
            name="faculty",
        ),
        migrations.RemoveField(
            model_name="passwordresettoken",
            name="user",
        ),
        migrations.RemoveField(
            model_name="rolepermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="personaddress",
            name="person",
        ),
        migrations.RemoveField(
            model_name="rolepermission",
            name="role",
        ),
        migrations.RemoveField(
            model_name="studentdocument",
            name="student",
        ),
        migrations.RemoveField(
            model_name="studentguardian",
            name="student",
        ),
        migrations.RemoveField(
            model_name="usersession",
            name="user",
        ),
        migrations.DeleteModel(
            name="Address",
        ),
        migrations.DeleteModel(
            name="AuditLog",
        ),
        migrations.DeleteModel(
            name="FacultySalary",
        ),
        migrations.DeleteModel(
            name="PasswordResetToken",
        ),
        migrations.DeleteModel(
            name="Permission",
        ),
        migrations.DeleteModel(
            name="PersonAddress",
        ),
        migrations.DeleteModel(
            name="RolePermission",
        ),
        migrations.DeleteModel(
            name="StudentDocument",
        ),
        migrations.DeleteModel(
            name="StudentGuardian",
        ),
        migrations.DeleteModel(
            name="UserSession",
        ),
    ]
