# Generated by Django 5.2.17 on 2026-09-23 19:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0002_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="course",
            options={"ordering": ("name",)},
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ("name",)},
        ),
    ]
