# Generated by Django 5.2.17 on 2026-09-23 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0003_alter_course_options_alter_department_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="AcademicCalendar",
            fields=[
                ("calendar_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("event_name", models.CharField(max_length=150)),
                ("event_type", models.CharField(max_length=50)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="AcademicYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_code", models.CharField(max_length=9, unique=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("is_current", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="Exam",
            fields=[
                ("exam_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("exam_name", models.CharField(max_length=150)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name="ExamSubject",
            fields=[
                (
                    "exam_subject_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("exam_date", models.DateField()),
                ("max_marks", models.PositiveIntegerField()),
                ("passing_marks", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="ExamType",
            fields=[
                (
                    "exam_type_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="GradeCard",
            fields=[
                (
                    "grade_card_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("certificate_number", models.CharField(max_length=80, unique=True)),
                ("issue_date", models.DateField()),
                ("pdf_url", models.URLField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="GradingScale",
            fields=[
                ("grade_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("grade", models.CharField(max_length=10)),
                ("min_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("max_percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                ("grade_point", models.DecimalField(decimal_places=2, max_digits=4)),
            ],
        ),
        migrations.CreateModel(
            name="Program",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("program_code", models.CharField(max_length=20, unique=True)),
                ("program_name", models.CharField(max_length=150)),
                ("degree_type", models.CharField(blank=True, max_length=50)),
                ("duration_years", models.PositiveSmallIntegerField(default=3)),
            ],
            options={
                "ordering": ("program_name",),
            },
        ),
        migrations.CreateModel(
            name="ProgramSubject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_core", models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                ("room_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("room_code", models.CharField(max_length=30, unique=True)),
                ("building", models.CharField(blank=True, max_length=100)),
                ("floor", models.CharField(blank=True, max_length=30)),
                ("room_type", models.CharField(blank=True, max_length=50)),
                ("capacity", models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name="Section",
            fields=[
                ("section_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("section_code", models.CharField(max_length=30)),
                ("capacity", models.PositiveIntegerField(default=60)),
            ],
        ),
        migrations.CreateModel(
            name="SectionStudent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("assigned_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("semester_number", models.PositiveSmallIntegerField()),
                ("name", models.CharField(blank=True, max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name="StudentMark",
            fields=[
                ("marks_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("marks_obtained", models.DecimalField(decimal_places=2, max_digits=7)),
                (
                    "internal_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                (
                    "practical_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=7),
                ),
                ("remarks", models.TextField(blank=True)),
                ("entered_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="StudentResult",
            fields=[
                ("result_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("total_marks", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "obtained_marks",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("percentage", models.DecimalField(decimal_places=2, max_digits=5)),
                (
                    "sgpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                (
                    "cgpa",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=4, null=True
                    ),
                ),
                ("result_status", models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                ("slot_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("day_of_week", models.PositiveSmallIntegerField()),
                ("start_time", models.TimeField()),
                ("end_time", models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name="Timetable",
            fields=[
                (
                    "timetable_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.AlterModelOptions(
            name="department",
            options={"ordering": ("department_name",)},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"ordering": ("subject_code",)},
        ),
        migrations.RenameField(
            model_name="department",
            old_name="code",
            new_name="department_code",
        ),
        migrations.RenameField(
            model_name="department",
            old_name="name",
            new_name="department_name",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="code",
            new_name="subject_code",
        ),
        migrations.RenameField(
            model_name="subject",
            old_name="name",
            new_name="subject_name",
        ),
        migrations.AlterUniqueTogether(
            name="enrollment",
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name="subject",
            name="faculty",
        ),
        migrations.RemoveField(
            model_name="subject",
            name="semester",
        ),
    ]
