# Generated by Django 5.2.17 on 2026-09-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "academics",
            "0005_department_head_faculty_enrollment_enrollment_date_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="enrollment",
            name="enrollment_id",
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
    ]
