# Generated by Django 5.2.17 on 2026-09-23 21:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0006_alter_enrollment_enrollment_id"),
        ("accounts", "0005_seed_roles_and_assign_existing_users"),
    ]

    operations = [
        migrations.CreateModel(
            name="FacultySubject",
            fields=[
                (
                    "faculty_subject_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faculty_assignments",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "faculty",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subject_assignments",
                        to="accounts.facultyprofile",
                    ),
                ),
                (
                    "section",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faculty_assignments",
                        to="academics.section",
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faculty_assignments",
                        to="academics.semester",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="faculty_assignments",
                        to="academics.subject",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=(
                            "faculty",
                            "subject",
                            "academic_year",
                            "semester",
                            "section",
                        ),
                        name="unique_faculty_subject_assignment",
                    )
                ],
            },
        ),
    ]
