# Generated by Django 5.2.17 on 2026-09-23 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0007_facultysubject"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="facultysubject",
            options={"ordering": ("academic_year", "semester", "section", "subject")},
        ),
    ]
