# Generated by Django 5.2.17 on 2026-09-26 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0009_remove_academiccalendar_academic_year_and_more"),
        ("attendance", "0004_remove_facultyattendance_faculty_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Section",
        ),
        migrations.DeleteModel(
            name="SectionStudent",
        ),
        migrations.DeleteModel(
            name="StudentMark",
        ),
        migrations.DeleteModel(
            name="StudentResult",
        ),
        migrations.DeleteModel(
            name="TimeSlot",
        ),
        migrations.DeleteModel(
            name="Timetable",
        ),
    ]
