# Generated by Django 5.2.17 on 2026-09-24 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("attendance", "0002_leavetype_attendancesession_facultyattendance_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancesession",
            name="status",
            field=models.CharField(
                choices=[("SCHEDULED", "Scheduled"), ("COMPLETED", "Completed")],
                default="SCHEDULED",
                max_length=20,
            ),
        ),
    ]
