# Generated by Django 5.2.17 on 2026-09-26 05:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0009_remove_academiccalendar_academic_year_and_more"),
        ("attendance", "0003_attendancesession_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="facultyattendance",
            name="faculty",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="approved_by",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="leave_type",
        ),
        migrations.RemoveField(
            model_name="leaverequest",
            name="user",
        ),
        migrations.DeleteModel(
            name="Attendance",
        ),
        migrations.RemoveField(
            model_name="attendancesession",
            name="section",
        ),
        migrations.AddField(
            model_name="attendancesession",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="attendance_sessions",
                to="academics.semester",
            ),
        ),
        migrations.DeleteModel(
            name="FacultyAttendance",
        ),
        migrations.DeleteModel(
            name="LeaveType",
        ),
        migrations.DeleteModel(
            name="LeaveRequest",
        ),
    ]
