# Generated by Django 5.2.17 on 2026-09-26 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("communication", "0003_club_event_servicerequest_clubmembership_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clubmembership",
            name="club",
        ),
        migrations.RemoveField(
            model_name="clubmembership",
            name="student",
        ),
        migrations.RemoveField(
            model_name="eventregistration",
            name="event",
        ),
        migrations.RemoveField(
            model_name="eventregistration",
            name="student",
        ),
        migrations.RemoveField(
            model_name="messagelog",
            name="user",
        ),
        migrations.RemoveField(
            model_name="notice",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="noticerecipient",
            name="notice",
        ),
        migrations.RemoveField(
            model_name="noticerecipient",
            name="user",
        ),
        migrations.RemoveField(
            model_name="notification",
            name="user",
        ),
        migrations.RemoveField(
            model_name="postcomment",
            name="post",
        ),
        migrations.RemoveField(
            model_name="postcomment",
            name="user",
        ),
        migrations.RemoveField(
            model_name="postlike",
            name="post",
        ),
        migrations.RemoveField(
            model_name="postlike",
            name="user",
        ),
        migrations.RemoveField(
            model_name="servicerequest",
            name="student",
        ),
        migrations.AlterModelOptions(
            name="post",
            options={"ordering": ("-created_at",)},
        ),
        migrations.DeleteModel(
            name="Club",
        ),
        migrations.DeleteModel(
            name="ClubMembership",
        ),
        migrations.DeleteModel(
            name="Event",
        ),
        migrations.DeleteModel(
            name="EventRegistration",
        ),
        migrations.DeleteModel(
            name="MessageLog",
        ),
        migrations.DeleteModel(
            name="Notice",
        ),
        migrations.DeleteModel(
            name="NoticeRecipient",
        ),
        migrations.DeleteModel(
            name="Notification",
        ),
        migrations.DeleteModel(
            name="PostComment",
        ),
        migrations.DeleteModel(
            name="PostLike",
        ),
        migrations.DeleteModel(
            name="ServiceRequest",
        ),
    ]
