# Generated by Django 5.2.17 on 2026-09-23 21:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0004_academiccalendar_academicyear_exam_examsubject_and_more"),
        ("accounts", "0003_address_permission_person_role_and_more"),
        ("fees", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeeCategory",
            fields=[
                (
                    "fee_category_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("category_code", models.CharField(max_length=30, unique=True)),
                ("category_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="FeeInvoice",
            fields=[
                ("invoice_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("invoice_number", models.CharField(max_length=50, unique=True)),
                ("invoice_date", models.DateField()),
                ("due_date", models.DateField()),
                ("total_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("status", models.CharField(default="PENDING", max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name="Scholarship",
            fields=[
                (
                    "scholarship_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=150)),
                ("description", models.TextField(blank=True)),
                (
                    "percentage",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                (
                    "max_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feestructure",
            name="academic_year_record",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_structures",
                to="academics.academicyear",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="program",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_structures",
                to="academics.program",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="student_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="accounts.studentprofile",
            ),
        ),
        migrations.AddField(
            model_name="feestructure",
            name="fee_category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="fee_structures",
                to="fees.feecategory",
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="invoice",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="fees.feeinvoice",
            ),
        ),
        migrations.CreateModel(
            name="FeeInvoiceItem",
            fields=[
                (
                    "invoice_item_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "fee_category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="invoice_items",
                        to="fees.feecategory",
                    ),
                ),
                (
                    "invoice",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="fees.feeinvoice",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Receipt",
            fields=[
                ("receipt_id", models.BigAutoField(primary_key=True, serialize=False)),
                ("receipt_number", models.CharField(max_length=50, unique=True)),
                ("receipt_url", models.URLField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "payment",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="receipt",
                        to="fees.payment",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="StudentFeeAccount",
            fields=[
                (
                    "fee_account_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "total_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "pending_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("status", models.CharField(default="PENDING", max_length=30)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="student_fee_accounts",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="fee_accounts",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="feeinvoice",
            name="fee_account",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invoices",
                to="fees.studentfeeaccount",
            ),
        ),
        migrations.CreateModel(
            name="StudentScholarship",
            fields=[
                (
                    "student_scholarship_id",
                    models.BigAutoField(primary_key=True, serialize=False),
                ),
                (
                    "approved_amount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("status", models.CharField(default="PENDING", max_length=30)),
                (
                    "academic_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="scholarships",
                        to="academics.academicyear",
                    ),
                ),
                (
                    "scholarship",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="awards",
                        to="fees.scholarship",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scholarships",
                        to="accounts.studentprofile",
                    ),
                ),
            ],
        ),
        migrations.AddConstraint(
            model_name="studentfeeaccount",
            constraint=models.UniqueConstraint(
                fields=("student", "academic_year"), name="unique_student_fee_account"
            ),
        ),
    ]
