# Generated by Django 5.2.17 on 2026-09-23 21:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fees", "0002_feecategory_feeinvoice_scholarship_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="fee_structure",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="payments",
                to="fees.feestructure",
            ),
        ),
    ]
